- name: Construir y subir imagen Docker
  run: |
    docker build -t us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/recomen/ci-cd-ia:latest .
    docker push us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/recomen/ci-cd-ia:latest
