name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Autenticarse en Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar Docker para GCP
        run: gcloud auth configure-docker

      - name: Construir y subir imagen Docker
        run: |
          docker build -t gcr.io/still-nebula-450101-k2/mi-proyecto:latest .
          docker push gcr.io/still-nebula-450101-k2/mi-proyecto:latest

      - name: Desplegar en Cloud Run
        run: |
          gcloud run deploy mi-proyecto \
            --image gcr.io/still-nebula-450101-k2/mi-proyecto:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
